Teams = [
  {fullName: "Atlanta Hawks", teamId: 1},
  {fullName: "Boston Celtics", teamId: 2},
  {fullName: "Brooklyn Nets", teamId: 4},
  {fullName: "Charlotte Hornets", teamId: 5},
  {fullName: "Chicago Bulls", teamId: 6},
  {fullName: "Cleveland Cavaliers", teamId: 7},
  {fullName: "Dallas Mavericks", teamId: 8},
  {fullName: "Denver Nuggets", teamId: 9},
  {fullName: "Detroit Pistons", teamId: 10},
  {fullName: "Golden State Warriors", teamId: 11},
  {fullName: "Houston Rockets", teamId: 14},
  {fullName: "Indiana Pacers", teamId: 15},
  {fullName: "LA Clippers", teamId: 16},
  {fullName: "Los Angeles Lakers", teamId: 17},
  {fullName: "Memphis Grizzlies", teamId: 19},
  {fullName: "Miami Heat", teamId: 20},
  {fullName: "Milwaukee Bucks", teamId: 21},
  {fullName: "Minnesota Timberwolves", teamId: 22},
  {fullName: "New Orleans Pelicans", teamId: 23},
  {fullName: "New York Knicks", teamId: 24},
  {fullName: "Oklahoma City" Thunder, teamId: 25},
  {fullName: "Orlando Magic", teamId: 26},
  {fullName: "Philadelphia 76ers", teamId: 27},
  {fullName: "Phoenix Suns", teamId: 28},
  {fullName: "Portland Trail Blazers", teamId: 29},
  {fullName: "Sacramento Kings", teamId: 30},
  {fullName: "San Antonio Spurs", teamId: 31},
  {fullName: "Toronto Raptors", teamId: 38},
  {fullName: "Utah Jazz", teamId: 40},
  {fullName: "Washington Wizards", teamId: 41},
]