# Generated by Django 3.0.8 on 2020-09-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('W', 'West'), ('E', 'East')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('AT', 'Atlantic'), ('CE', 'Central'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('PA', 'Pacific'), ('SW', 'Southwest')], max_length=10)),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='quiz.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('fullName', models.CharField(max_length=64)),
                ('teamId', models.IntegerField()),
                ('nickname', models.CharField(max_length=64)),
                ('logo', models.URLField()),
                ('shortName', models.CharField(max_length=10)),
                ('allStar', models.IntegerField()),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='quiz.Conference')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='quiz.Division')),
            ],
        ),
    ]
