# Generated by Django 3.0.8 on 2020-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(choices=[('west', 'West'), ('east', 'East')], max_length=64),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('atlantic', 'Atlantic'), ('central', 'Central'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('pacific', 'Pacific'), ('southwest', 'Southwest')], max_length=64),
        ),
    ]
