# Generated by Django 3.0.8 on 2020-09-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200910_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='conf',
        ),
    ]
